/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPixCreateRouteImport } from './routes/api/public/pix/create'
import { Route as ApiPublicPixStatusRouteImport } from './routes/api/public/pix/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixCreateRoute = ApiPublicPixCreateRouteImport.update({
  id: '/api/public/pix/create',
  path: '/api/public/pix/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixStatusRoute = ApiPublicPixStatusRouteImport.update({
  id: '/api/public/pix/status',
  path: '/api/public/pix/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/pix/create': typeof ApiPublicPixCreateRoute
  '/api/public/pix/status': typeof ApiPublicPixStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/pix/create': typeof ApiPublicPixCreateRoute
  '/api/public/pix/status': typeof ApiPublicPixStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/pix/create': typeof ApiPublicPixCreateRoute
  '/api/public/pix/status': typeof ApiPublicPixStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/pix/create' | '/api/public/pix/status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/pix/create' | '/api/public/pix/status'
  id: '__root__' | '/' | '/api/public/pix/create' | '/api/public/pix/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicPixCreateRoute: typeof ApiPublicPixCreateRoute
  ApiPublicPixStatusRoute: typeof ApiPublicPixStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix/create': {
      id: '/api/public/pix/create'
      path: '/api/public/pix/create'
      fullPath: '/api/public/pix/create'
      preLoaderRoute: typeof ApiPublicPixCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix/status': {
      id: '/api/public/pix/status'
      path: '/api/public/pix/status'
      fullPath: '/api/public/pix/status'
      preLoaderRoute: typeof ApiPublicPixStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicPixCreateRoute: ApiPublicPixCreateRoute,
  ApiPublicPixStatusRoute: ApiPublicPixStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
